import type { AnalysisResult } from "./agent.service.js";

export class ReasoningService {
  rankByConfidence(results: AnalysisResult[]): AnalysisResult[] {
    return [...results].sort((left, right) => right.confidence - left.confidence);
  }

  summarize(results: AnalysisResult[]): string {
    if (results.length === 0) {
      return "No reasoning output available.";
    }

    const agentNames = results.map((result) => result.agentName).join(", ");
    return `Reasoning generated by ${agentNames}.`;
  }
}
